name: k8s cluster AWS spinup
on: 
  workflow_dispatch:

jobs:
  create-k8s-cluster:
    runs-on: ubuntu-20.04
    container: 
      image: andreleo/ansible-terraform:latest
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        TF_VAR_public_key: "${{ secrets.TF_VAR_public_key }}"
        TF_VAR_key_name: "${{ secrets.TF_VAR_key_name }}"
        TF_VAR_ami: "${{ secrets.TF_VAR_ami }}"
        TF_VAR_instance_type: "${{ secrets.TF_VAR_instance_type }}"
        TF_VAR_region: "${{ secrets.TF_VAR_region }}"
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Initialize Terraform
        run: terraform init
        working-directory: .

      - name: Apply Terraform
        run: terraform apply --auto-approve
        working-directory: .

      - name: Save private key in file on ssh folder
        run: mkdir -p ~/.ssh/ && echo "$PRIVATE_KEY" > ~/.ssh/id_rsa && unset PRIVATE_KEY && chmod 600 ~/.ssh/id_rsa

      - name: Apply Ansible playbook
        run: ansible-playbook -i ec2.py -u ubuntu --private-key ~/.ssh/id_rsa --ssh-common-args='-o StrictHostKeyChecking=no' site.yml